const express = require("express")
const router = express.Router()

const createBuzoRoute = require("./createBuzoRoute")
const createTeamRoute = require("./createTeamRoute")
const createMareaRoute = require("./createMareaRoute")
const createFaenaRoute = require("./createFaenaRoute")
const createClasificacionRoute = require("./createClasificacionRoute")
const createActividadRoute = require("./createActividadRoute")
const createInmersionRoute = require("./createInmersionRoute")
const createDataloggerRoute = require("./createDataloggerRoute")

const getBuzoRoute = require("./getBuzosByCompanyRoute")
const getTeamRoute = require("./getTeamsRoute")
const getMareaRoute = require("./getMareaRoute")
const getFaenasByMareaRoute = require("./getFaenasByMareaRoute")
const getClasificacionesRoute = require("./getClasificacionRoute")
const getActividadesFaenaByClasificacionRoute = require("./getActividadesFaenaByClasificacionesRoute")
const getInmersionByFaenaRoute = require("./getInmersionByFaenaRoute")
const getDataloggerByInmersionRoute = require("./getDataloggerByInmersionRoute")

const updateBuzoRoute = require("./udpateBuzoRoute")
const updateTeamRoute = require("./updateTeamRoute")
const updateMareaRoute = require("./updateMareaRoute")
const updateFaenaRoute = require("./updateFaenaRoute")
const updateClasificacionRoute = require("./updateClasificacionRoute")
const updateActividadFaenaRoute = require("./updateActividadRoute")
const updateInmersionRoute = require("./updateInmersionRoute")
const updateDataloggerRoute = require("./updateDataloggerRoute")

const deleteBuzoRoute = require("./deleteBuzoRoute")
const deleteTeamRoute = require("./deleteTeamRoute")
const deleteMareaRoute = require("./deleteMareaRoute")
const deleteFaenaRoute = require("./deleteFaenaRoute")
const deleteClasificacionRoute = require("./deleteClasificacionRoute")
const deleteActividadesFaenaRoute = require("./deleteActividadFaenaRoute")
const deleteInmersionRoute = require("./deleteInmersionRoute")
const deleteDataloggerRoute = require("./deleteDataloggerRoute")

router.use("/", createBuzoRoute)
router.use("/", createTeamRoute)
router.use("/", createMareaRoute)
router.use("/", createFaenaRoute)
router.use("/", createClasificacionRoute)
router.use("/", createActividadRoute)
router.use("/", createInmersionRoute)
router.use("/", createDataloggerRoute)

router.use("/", getBuzoRoute)
router.use("/", getTeamRoute)
router.use("/", getMareaRoute)
router.use("/", getFaenasByMareaRoute)
router.use("/", getClasificacionesRoute)
router.use("/", getActividadesFaenaByClasificacionRoute)
router.use("/", getInmersionByFaenaRoute)
router.use("/", getDataloggerByInmersionRoute)

router.use("/", updateBuzoRoute)
router.use("/", updateTeamRoute)
router.use("/", updateMareaRoute)
router.use("/", updateFaenaRoute)
router.use("/", updateClasificacionRoute)
router.use("/", updateActividadFaenaRoute)
router.use("/", updateInmersionRoute)
router.use("/", updateDataloggerRoute)

router.use("/", deleteBuzoRoute)
router.use("/", deleteTeamRoute)
router.use("/", deleteMareaRoute)
router.use("/", deleteFaenaRoute)
router.use("/", deleteClasificacionRoute)
router.use("/", deleteActividadesFaenaRoute)
router.use("/", deleteInmersionRoute)
router.use("/", deleteDataloggerRoute)

module.exports = router